version: 2

project_name: terrastate

before:
  hooks:
    - go mod download

builds:
  - main: .
    binary: terrastate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/janritter/terrastate/cmd.version={{.Version}}
      - -X github.com/janritter/terrastate/cmd.gitSha={{.Commit}}
      - -X github.com/janritter/terrastate/cmd.buildTime={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

release:
  github:
    owner: janritter
    name: terrastate

homebrew_casks:
  - name: terrastate
    homepage: https://github.com/janritter/terrastate
    description: Tool to manage multiple states in Terraform - Allows Multi account setups
    directory: Casks
    commit_msg_template: "chore: brew cask update for {{ .ProjectName }} version {{ .Tag }} [skip ci]"
    commit_author:
      name: goreleaserbot
      email: git+circleci@janrtr.de
    repository:
      owner: janritter
      name: homebrew-terrastate
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terrastate"]
          end

changelog:
  disable: true
