stages:
  - test

  - name: release
    if: branch = master AND type != pull_request

  - name: build
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: test
      language: go
      go: "stable"
      before_script:
        # Setup dependency management tool (go dep)
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        - chmod +x $GOPATH/bin/dep
      script:
        - make prepare
        - make tests

    - stage: release
      language: node_js
      install:
        - . $HOME/.nvm/nvm.sh
        - nvm install stable
        - nvm use stable
        - npm install @semantic-release/changelog && npm install @semantic-release/git
      script:
        - npx semantic-release

    - stage: build
      language: go
      go: "stable"
      before_script:
        # Setup dependency management tool (go dep)
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        - chmod +x $GOPATH/bin/dep
         # Install Python 3
        - sudo apt-get install python3 python3-pip -y
        # Use latest master version, which includes the git tag from the release step
        - git checkout master
      script:
        - go get github.com/mitchellh/gox
        - go get github.com/tcnksm/ghr
        - make prepare
        - NOW=$(date +'%Y-%m-%d_%T')
        - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}" -ldflags "-X github.com/janritter/terrastate/cmd.gitSha=`git rev-parse HEAD` -X github.com/janritter/terrastate/cmd.buildTime=$NOW -X github.com/janritter/terrastate/cmd.version=`git describe --abbrev=0 --tags`" -arch="amd64 386" -os="linux darwin windows"
        - ghr --username janritter --token $GITHUB_TOKEN --replace $(git describe --abbrev=0 --tags) dist/
        
        # Create new Homebrew formula
        - export FILE_HASH=`sha256sum dist/darwin_amd64_terrastate | awk '{print $1}'`
        - export VERSION=`git describe --abbrev=0 --tags`
        - git clone https://${GITHUB_TOKEN}@github.com/janritter/homebrew-terrastate.git
        - cd homebrew-terrastate
        - pip3 install --user jinja2
        - python3 generateFormula.py
        - 'git add terrastate.rb && git commit -m "chore: deployment of version $VERSION - $NOW" && git push'
