version: 2.1

orbs: 
  semantic-release: trustedshops-public/semantic-release@6.1.0

jobs:
  test:
    docker:
      - image: cimg/go:1.27
    working_directory: ~/go/src/github.com/janritter/terrastate
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            make prepare
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
            mkdir -p /tmp/test-results
      - run:
          name: Run tests
          command: |
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile /tmp/test-results/gotestsum-report.xml -- -coverprofile=c.out $PACKAGE_NAMES
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: /tmp/test-results
      - run:
          name: Install Terraform
          command: |
            curl -sSfL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.15.1/terraform_1.15.1_linux_amd64.zip
            sudo unzip -o /tmp/terraform.zip -d /usr/local/bin
      - run:
          name: Run terrastate against test/test.tfvars and validate the generated terrastate.tf
          command: make tests-e2e

  build:
    docker:
      - image: cimg/go:1.27
    working_directory: ~/go/src/github.com/janritter/terrastate
    steps:
      - checkout
      - run:
          name: Get latest main version, which includes the git tag from the release step
          command: |
            git checkout main
            git pull
      - run:
          name: Install GoReleaser
          command: |
            curl -sSfL https://goreleaser.com/static/run | GOVERSION_FLAGS='' bash -s -- --version
            curl -sSfL https://github.com/goreleaser/goreleaser/releases/latest/download/goreleaser_Linux_x86_64.tar.gz | tar -xz -C /tmp goreleaser
            sudo mv /tmp/goreleaser /usr/local/bin/goreleaser
      - run:
          name: Release
          command: goreleaser release --clean

workflows:
  continuous:
    jobs:
      - test:
          filters:
            branches:
              only:
              - /feat\/.*/
              - /chore\/.*/
              - /fix\/.*/
              - /test\/.*/
              - /refactor\/.*/
              - /perf\/.*/
              - /dependabot\/.*/
              - /renovate\/.*/
              - /pull\/.*/
              - main
      - semantic-release/with_changelog_github_config:
          name: release
          requires:
            - test
          filters:
            branches:
              only:
                - main
          context:
            - github-release
      - build:
          requires:
            - release
          filters:
            branches:
              only:
                - main
          context:
            - github-release
