// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	types "github.com/janritter/terrastate/backend/types"
	mock "github.com/stretchr/testify/mock"
)

// CreatorAPI is an autogenerated mock type for the CreatorAPI type
type CreatorAPI struct {
	mock.Mock
}

// Create provides a mock function with given fields: stateFileAttributes, backend
func (_m *CreatorAPI) Create(stateFileAttributes []*types.StateFileAttribute, backend string) {
	_m.Called(stateFileAttributes, backend)
}
