// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	types "github.com/janritter/terrastate/backend/types"
	mock "github.com/stretchr/testify/mock"
)

// HelperAPI is an autogenerated mock type for the HelperAPI type
type HelperAPI struct {
	mock.Mock
}

// PrintStateFileAttributes provides a mock function with given fields: attributes
func (_m *HelperAPI) PrintStateFileAttributes(attributes []*types.StateFileAttribute) {
	_m.Called(attributes)
}

// RemoveDotTerraformFolder provides a mock function with given fields: shouldRemove
func (_m *HelperAPI) RemoveDotTerraformFolder(shouldRemove bool) {
	_m.Called(shouldRemove)
}
