// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/janritter/terrastate/backend/types"
)

// ParserAPI is an autogenerated mock type for the ParserAPI type
type ParserAPI struct {
	mock.Mock
}

// Gather provides a mock function with given fields: stateFileAttributes
func (_m *ParserAPI) Gather(stateFileAttributes []*types.StateFileAttribute) {
	_m.Called(stateFileAttributes)
}

// GatherTerrastateVariables provides a mock function with given fields: terrastateAttribute
func (_m *ParserAPI) GatherTerrastateVariables(terrastateAttribute map[string]*types.TerrastateAttribute) {
	_m.Called(terrastateAttribute)
}
