# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terrastate < Formula
  desc "Tool to manage multiple states in Terraform - Allows Multi account setups"
  homepage "https://github.com/janritter/terrastate"
  version "2.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/janritter/terrastate/releases/download/2.2.0/terrastate_darwin_amd64.tar.gz"
      sha256 "7af6e42d60c2079d52268f7df77efb9316c4a6d514ebaefb53157b9bb515161f"

      define_method(:install) do
        bin.install "terrastate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/janritter/terrastate/releases/download/2.2.0/terrastate_darwin_arm64.tar.gz"
      sha256 "a12571d3fb687b70871ae106c8a34a75b456332046207e831fdcd13a3b277d59"

      define_method(:install) do
        bin.install "terrastate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/janritter/terrastate/releases/download/2.2.0/terrastate_linux_amd64.tar.gz"
      sha256 "9f017f78614f96bf51a3e115bdc11816c0b0ecf63dc458554ed207c53920bf20"
      define_method(:install) do
        bin.install "terrastate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/janritter/terrastate/releases/download/2.2.0/terrastate_linux_arm64.tar.gz"
      sha256 "b3339a714e169997795a5029a8721625aef91f92b08fd2ec550db6dcb618de0d"
      define_method(:install) do
        bin.install "terrastate"
      end
    end
  end

  test do
    system "#{bin}/terrastate version"
  end
end
